Securing the external HTTP routes with AIP (#1361)
* modifications to deploy app of apps in prod

* point prod app of apps to separate folder

* bugfix - argo worfklows namespace non existent

* deploying first prod app - gateway

* fix value passdown to app of apps

* parametrise target revision

* syntax fix

* revert quotes in values

* target revision bugfix

* target revision bugfix

* target revision bugfix

* target revision bugfix

* try reference deeper levels from argotf manifest

* emty string

* emty string

* attempt using parameters

# Conflicts:
#	infra/argo/app-of-apps/values.yaml

* try tpl

* use two sources

* add target revision

* adding chart into vars folder

* refactor

* replacements of vars in gateway

* braces change

* spec source

* spec source - helm

* spec source - helm 2

* spec source - helm 3

* spec source - helm 4

* replace all values by dummies

* fix bracket spaces

* add value for server

* hardcode again some values

* add helm parameter references to templates

* add helm params

* fully templating moa service

* copy moa to prodtest

* remove space in between brackets for argo workflows

* replace space in between brackets everywhere

* replace space in between brackets everywhere

* adapt other templates

* parametrise values in helm charts

* repoint the prod app from applications_prodtest to applications

* add sync wave 1 to service monitor

* stash 2 failing app

* re-enable kube-prometheus app

* add ApplyOutOfSyncOnly to kube prom stack

* prune - false

* replace = false

* enable argo workflows

* comment out sh script in data release

* try different way of passing mlflow values to fix mlflow: - tracking.args: Invalid type. Expected: array, given: string

* try different way of passing mlflow values to fix mlflow: - tracking.args: Invalid type. Expected: array, given: string

* rename all keys of pg password to "password"

* Revert "rename all keys of pg password to "password""

This reverts commit 5eb936e92633a9064c7a700d3b948e45a6e9b708.

* add second key to the secret

* formatting

* bugfix gs missing

* add comment

* fixing the bug:

Error: execution error at (Neo4J DB/charts/neo4j/templates/neo4j-statefulset.yaml:52:63): config values must be strings. server value: map[bolt:map[advertised_address:neo4j.prod.everycure.org:7687] default_advertised_address:neo4j.prod.everycure.org] type: map (put values in double quotes so they are treated as strings in yaml) Use --debug flag to render out invalid YAML

* fixing the bug:

Error: execution error at (Neo4J DB/charts/neo4j/templates/neo4j-statefulset.yaml:52:63): config values must be strings. server value: map[bolt:map[advertised_address:neo4j.prod.everycure.org:7687] default_advertised_address:neo4j.prod.everycure.org] type: map (put values in double quotes so they are treated as strings in yaml) Use --debug flag to render out invalid YAML

* fixing the bug:

Error: execution error at (Neo4J DB/charts/neo4j/templates/neo4j-statefulset.yaml:52:63): config values must be strings. server value: map[bolt:map[advertised_address:neo4j.prod.everycure.org:7687] default_advertised_address:neo4j.prod.everycure.org] type: map (put values in double quotes so they are treated as strings in yaml) Use --debug flag to render out invalid YAML

* fixing the bug:

Error: execution error at (Neo4J DB/charts/neo4j/templates/neo4j-statefulset.yaml:52:63): config values must be strings. server value: map[bolt:map[advertised_address:neo4j.prod.everycure.org:7687] default_advertised_address:neo4j.prod.everycure.org] type: map (put values in double quotes so they are treated as strings in yaml) Use --debug flag to render out invalid YAML

* test data release app debug

* test data release app debug

* bump prom stack

* cleanup data release zone in prod

* add new git repo credential for matrix-ux

* add backups

* change label to repo creds

* add persistence to mlflow

* comment out persistence in mlflow

* bring back persistence in mlflow

* emable persistence in neo4j

* fix emable persistence in neo4j

* remove emable persistence in neo4j as it had no effect

* add vars

* variable cleanup

* remove random readme

* temporarily disable mlflow pvc deletion protection

* temporarily enable mlflow pvc deletion protection

* temporarily disable mlflow pvc deletion protection

* temporarily enable mlflow pvc deletion protection

* debug - test delete neo4j

* Revert "debug - test delete neo4j"

This reverts commit 1eef24a2661c6b7c51b493a6c58bd4a41a1ceebb.

* debug - test delete neo4j

* Revert "debug - test delete neo4j"

This reverts commit 7bc5fea0ecf886da1a1a280bf9885a5f944b71c5.

* bugfix neo4j prod dns not available

* remove sync wave which wasn't needed

* delete ai annotation

* replace dummy with dummy replaced with ...

* remove argo-workflows namespace creation

* split k8s_secrets for dev and prod

* change passwords for Neo4j and PotGreSQL

* refer to prod instead of prd

* retrigger CI check by dummy line

* Use different secrets for Production (#1334)

* Parametrise argocd apps to enable multi-env deployments. (#1319)

* modifications to deploy app of apps in prod

* point prod app of apps to separate folder

* bugfix - argo worfklows namespace non existent

* deploying first prod app - gateway

* fix value passdown to app of apps

* parametrise target revision

* syntax fix

* revert quotes in values

* target revision bugfix

* target revision bugfix

* target revision bugfix

* target revision bugfix

* try reference deeper levels from argotf manifest

* emty string

* emty string

* attempt using parameters

# Conflicts:
#	infra/argo/app-of-apps/values.yaml

* try tpl

* use two sources

* add target revision

* adding chart into vars folder

* refactor

* replacements of vars in gateway

* braces change

* spec source

* spec source - helm

* spec source - helm 2

* spec source - helm 3

* spec source - helm 4

* replace all values by dummies

* fix bracket spaces

* add value for server

* hardcode again some values

* add helm parameter references to templates

* add helm params

* fully templating moa service

* copy moa to prodtest

* remove space in between brackets for argo workflows

* replace space in between brackets everywhere

* replace space in between brackets everywhere

* adapt other templates

* parametrise values in helm charts

* repoint the prod app from applications_prodtest to applications

* add sync wave 1 to service monitor

* stash 2 failing app

* re-enable kube-prometheus app

* add ApplyOutOfSyncOnly to kube prom stack

* prune - false

* replace = false

* enable argo workflows

* comment out sh script in data release

* try different way of passing mlflow values to fix mlflow: - tracking.args: Invalid type. Expected: array, given: string

* try different way of passing mlflow values to fix mlflow: - tracking.args: Invalid type. Expected: array, given: string

* rename all keys of pg password to "password"

* Revert "rename all keys of pg password to "password""

This reverts commit 5eb936e92633a9064c7a700d3b948e45a6e9b708.

* add second key to the secret

* formatting

* bugfix gs missing

* add comment

* fixing the bug:

Error: execution error at (Neo4J DB/charts/neo4j/templates/neo4j-statefulset.yaml:52:63): config values must be strings. server value: map[bolt:map[advertised_address:neo4j.prod.everycure.org:7687] default_advertised_address:neo4j.prod.everycure.org] type: map (put values in double quotes so they are treated as strings in yaml) Use --debug flag to render out invalid YAML

* fixing the bug:

Error: execution error at (Neo4J DB/charts/neo4j/templates/neo4j-statefulset.yaml:52:63): config values must be strings. server value: map[bolt:map[advertised_address:neo4j.prod.everycure.org:7687] default_advertised_address:neo4j.prod.everycure.org] type: map (put values in double quotes so they are treated as strings in yaml) Use --debug flag to render out invalid YAML

* fixing the bug:

Error: execution error at (Neo4J DB/charts/neo4j/templates/neo4j-statefulset.yaml:52:63): config values must be strings. server value: map[bolt:map[advertised_address:neo4j.prod.everycure.org:7687] default_advertised_address:neo4j.prod.everycure.org] type: map (put values in double quotes so they are treated as strings in yaml) Use --debug flag to render out invalid YAML

* fixing the bug:

Error: execution error at (Neo4J DB/charts/neo4j/templates/neo4j-statefulset.yaml:52:63): config values must be strings. server value: map[bolt:map[advertised_address:neo4j.prod.everycure.org:7687] default_advertised_address:neo4j.prod.everycure.org] type: map (put values in double quotes so they are treated as strings in yaml) Use --debug flag to render out invalid YAML

* test data release app debug

* test data release app debug

* bump prom stack

* cleanup data release zone in prod

* add new git repo credential for matrix-ux

* add backups

* change label to repo creds

* add persistence to mlflow

* comment out persistence in mlflow

* bring back persistence in mlflow

* emable persistence in neo4j

* fix emable persistence in neo4j

* remove emable persistence in neo4j as it had no effect

* add vars

* variable cleanup

* remove random readme

* temporarily disable mlflow pvc deletion protection

* temporarily enable mlflow pvc deletion protection

* temporarily disable mlflow pvc deletion protection

* temporarily enable mlflow pvc deletion protection

* debug - test delete neo4j

* Revert "debug - test delete neo4j"

This reverts commit 1eef24a2661c6b7c51b493a6c58bd4a41a1ceebb.

* debug - test delete neo4j

* Revert "debug - test delete neo4j"

This reverts commit 7bc5fea0ecf886da1a1a280bf9885a5f944b71c5.

* bugfix neo4j prod dns not available

* remove sync wave which wasn't needed

* delete ai annotation

* replace dummy with dummy replaced with ...

* remove argo-workflows namespace creation

---------

Co-authored-by: Oliver Willekens <4733178+oliverw1@users.noreply.github.com>
Co-authored-by: Pascal Brokmeier <pascal@everycure.org>

* prune = true in app of apps (#1332)

* split k8s_secrets for dev and prod

* change passwords for Neo4j and PotGreSQL

* refer to prod instead of prd

* retrigger CI check by dummy line

---------

Co-authored-by: Emil <emil.krause.44@gmail.com>
Co-authored-by: Pascal Brokmeier <pascal@everycure.org>

* change password - pipe at the end not coming across easily

* password gets through, but partially due to spaces

* restore password for mysql-postgres to dev's

* deleting two secret files, that have been refactored and have been moved, to dev|prod folders, appeared here due to the merge of infra into infra-prod-debug

* auto-enable IAP for all apps using iac (#1360)

* auto-enable IAP for all apps using iac

* fix external secret reference in IAP

* edit definition of ExternalSecret

* replace _ with - in the external secret name

* add aip_oauth_client_id to gateway app template

* fix unwanted double space

* test - apply gcp backend policy to namespace

* applying backend policy only to mlflow

* add externalsecret for iap to mlflow app

* fix double space

* revert trying to set a namespace-wirde GCP backend policy

* Add GCP backend policy to: bte-trapi, argocd, argo workflows

* add helm arg client id to bte-trapi, argo workflows

* fix bad whitespace

* add gcp backend policy to grafana

* add IAP for kube-prometheus-stack-prometheus

* adding client id for IAP in dev

* add client secret for IAP in dev

* delete gcp backend policy from gateway

* add docs

* add docs - touchup

---------

Co-authored-by: Oliver Willekens <4733178+oliverw1@users.noreply.github.com>
Co-authored-by: Pascal Brokmeier <pascal@everycure.org>